name: Pak-RV-Core

on: [push, pull_request]

jobs:

  Pak-RV-Core-test:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3
      with:
        path: Pak-RV-Core

    - name: Install Verilator, Sail and cocotb
      run: |
        sudo apt-get install -y python3-setuptools
        echo 'deb http://download.opensuse.org/repositories/home:/phiwag:/edatools/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:phiwag:edatools.list
        curl -fsSL https://download.opensuse.org/repositories/home:phiwag:edatools/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_phiwag_edatools.gpg > /dev/null
        sudo apt-get update
        sudo apt-get upgrade
        set -e

        # Get directory of script
        src_path=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)
        
        sudo apt-get install -y git perl python3 make autoconf g++ flex bison ccache
        sudo apt-get install -y libunwind-dev libgoogle-perftools-dev numactl perl-doc help2man
        sudo apt-get install -y libfl2
        sudo apt-get install -y libfl-dev
        sudo apt-get install -y zlib1g zlib1g-dev
        
        git clone https://github.com/AhsanAliUet/tools
        cd tools
        tar -xzvf verilator.tar.gz
        tar -xzvf sail_cSim.tar.gz
        cd ..
        echo $GITHUB_WORKSPACE/tools/verilator >> $GITHUB_PATH
        echo $GITHUB_WORKSPACE/tools/sail_cSim >> $GITHUB_PATH

        pip3 install cocotb
        pip3 install git+https://github.com/riscv/riscof.git

    - name: Setup toolchain
      run: |
        wget https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-4.0.0/riscv32-unknown-elf.gcc-12.1.0.tar.gz
        tar -xzf riscv32-unknown-elf.gcc-12.1.0.tar.gz
        echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH

    - name: Run Compliance Verification Framework
      run: |
        cd Pak-RV-Core/verif/riscof_compliance
        chmod +x run-compliance.sh
        ./run-compliance.sh