name: Pak-RV-Core

on: [push, pull_request]

jobs:

  Pak-RV-Core-test:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3
      with:
        path: Pak-RV-Core

    - name: Install verilator and cocotb
      run: |
        sudo apt-get install -y python3-setuptools
        echo 'deb http://download.opensuse.org/repositories/home:/phiwag:/edatools/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:phiwag:edatools.list
        curl -fsSL https://download.opensuse.org/repositories/home:phiwag:edatools/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_phiwag_edatools.gpg > /dev/null
        sudo apt update
        sudo apt install verilator
        pip3 install cocotb

    - name: Setup toolchain
      run: |
        wget https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-4.0.0/riscv32-unknown-elf.gcc-12.1.0.tar.gz
        tar -xzf riscv32-unknown-elf.gcc-12.1.0.tar.gz
        echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH

    - name: Run Verification Framework
      run: |
        cd Pak-RV-Core
        make all