name: Pak-RV-Core

on: [push, pull_request]

jobs:

  Pak-RV-Core-test:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3
      with:
        path: Pak-RV-Core

    - name: Install Verilator, Sail, RISC-OF and Cocotb
      run: |

        set -e                 # exit immediately exit with non-zero value (or throw error and stop the CI/CD)

        git clone https://github.com/AhsanAliUet/tools
        cd tools
        tar -xzvf verilator.tar.gz
        tar -xzvf sail_cSim.tar.gz
        export VERILATOR_ROOT=$(pwd)/verilator
        export SAIL_ROOT=$(pwd)/sail_cSim
        cd ..
        echo $(VERILATOR_ROOT)/bin >> $GITHUB_PATH
        # echo $GITHUB_WORKSPACE/$(VERILATOR_ROOT)/include >> $GITHUB_PATH
        echo $(SAIL_ROOT) >> $GITHUB_PATH

        pip3 install cocotb
        pip3 install git+https://github.com/riscv/riscof.git

    - name: Setup RISC-V GNU toolchain
      run: |
        wget https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-4.0.0/riscv32-unknown-elf.gcc-12.1.0.tar.gz
        tar -xzf riscv32-unknown-elf.gcc-12.1.0.tar.gz
        echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH

    - name: Run Compliance Verification Framework
      run: |
        cd Pak-RV-Core
        git submodule update --init --recursive
        cd verif/riscof_compliance
        chmod +x run-compliance.sh
        ./run-compliance.sh